data <- read.csv("//Users/simranbafna/Downloads/excel sheets/csv files/Exploratory data2.csv")
attach(data)
View(data)
B1 <-  cbind (A1,A2,A3,A4,A5,C1,C2,C3,C4,C5,E1,E2,E3,E4,E5,N1,N2,N3,N4,N5,O1,O2,O3,O4,O5)
summary(B1)
cor(B1)
pca <-princomp(B1, scores = TRUE, cor= TRUE)
summary(pca)
loadings(pca)
plot.default(1:25)
screeplot(pca,type="line", main="scree plot")
biplot(pca)
pca$scores[1:10,]
fa1 <- factanal(B1, factor=5)
fa1
print(fa1, cutoff= .3)
fa10 <- factanal(B3, factor=5 , rotation = "varimax")
fa10
print(fa1,cutoff = .3)
print(fa10,cutoff = .3)
library(mirt)
scree(data, factors = FALSE)
scree.plot(data)
scree(data)
fa1(data,cor='poly')
fa1.parallel(data,cor='poly')
factor.plot(fa1(data,cor='poly'),cut=.2)
fa1.diagram(fa(data,cor='poly'),cut=.2)
irt.fa(data,plot=TRUE)
r=cor(B1)
library(psych)
alpha(data)
check.keys=TRUE
KMO(data)
cortest.bartlett(mydata)